spring:
  datasource:
    password: 2345678
    username: root
    url: jdbc:mysql://114.115.147.100:12138/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver